import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DarkLightProvider } from "./contexts/DarkLightContext";
import { AuthProvider } from "./contexts/AuthContext";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Temperature Checker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      {/* h-full / min-h-screen zwingt den Body auf volle Höhe */}
      <body className={`${inter.variable} min-h-screen flex flex-col justify-between`}>
        <AuthProvider>
          <DarkLightProvider>
            <Header />
            <main className="flex-1 flex flex-col justify-center">
              {children}
            </main>
          </DarkLightProvider>
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}