import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DarkLightProvider } from "./contexts/DarkLightContext";
import DarkModeToggle from "@/components/DarkModeToggle";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Temperature Checker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <DarkLightProvider>
          <DarkModeToggle />
          {children}
        </DarkLightProvider>
      </body>
    </html>
  );
}